spring:
  application:
    name: todo-app

  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

# MyBatis設定
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.example.todoapp.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

